name: cache-node-modules

on:
  push:
    branches: [develop]

defaults:
  run:
    shell: bash

jobs:
  cache:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: volta-cli/action@v4

      - uses: actions/checkout@v4

      - name: cache node_modules
        uses: ./.github/actions/cache-node-modules
