name: ci

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: volta-cli/action@v4

      - uses: actions/checkout@v4

      - name: cache node_modules
        uses: ./.github/actions/cache-node-modules

      - name: lint
        run: npm run lint

      - name: type-check
        run: npm run type-check

      - name: unit test
        run: npm run test:unit
